
# Menu
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about

# Profile
profile:
  avatar: /images/avatar.png
  subtitle: Life is fantastic!
  slogan: 经验是智慧之母。

# Daily Poetry, replace to profile.subtitle (Thanks to https://www.jinrishici.com/)
daily_poetry: true

# Basic
basic: 
  summary: true

# Socials
socials: 
  # Icon Style: fill / line
  iconstyle: line
  github: https://github.com/MyFaith
  weibo: https://weibo.com/234224964
  neteasemusic: http://music.163.com/#/user/home?id=33062246
  # twitter: 
  # facebook: 
  # instagram: 
  # youtube: 
  email: myfaith0725@gmail.com