<div class="footer animated fadeInDown">
    <div class="poweredby">
        <a href="https://zeuk.me">Desighed by Zeuk</a>
        <a href="https://github.com/MyFaith">Coding by MyFaith</a>
        <a href="https://github.com/MyFaith/hexo-theme-zozo">Theme Zozo</a>
        <a href="https://hexo.io">Proudly published with Hexo</a>
    </div>
    {% if theme.profile.slogan %}
        <div class="slogan">
            <span>{{ theme.profile.slogan }}</span>
        </div>
    {% endif %}
</div>